apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-argo-deploy
spec:
  selector:
    matchLabels:
      app: flask-myapp
  template:
    metadata:
      labels:
        app: flask-myapp
    spec:
      containers:
      - name: flask-argo-container
        image: sukhpreet2002/argo:78
        
        ports:
        - containerPort: 5000
